#cloud-config
# Author: Michal Koeckeis-Fresel
# License: MIT

# Update package cache and upgrade system
package_update: true
package_upgrade: true

# Install required packages
packages:
  - rsyslog
  - fail2ban
  - logrotate
  - sudo 
  - curl
  - wget

# Run commands after package installation
runcmd:
  # Download and execute the deploy basics script
  - curl -fsSL https://raw.githubusercontent.com/Michal-Koeckeis-Fresel/server-deployment/refs/heads/main/linux/deploy_scripts/01_deploy_basics.sh -o /tmp/01_deploy_basics.sh
  - chmod +x /tmp/01_deploy_basics.sh
  - /tmp/01_deploy_basics.sh
  - rm -f /tmp/01_deploy_basics.sh

# Reboot after all configuration is complete
power_state:
  mode: reboot
  message: "Rebooting after initial setup"
  timeout: 30
  condition: true