# BunkerWeb UI-Integrated Docker Compose Template (RELEASE CHANNEL SUPPORT)

x-ui-env: &ui-env
  # We anchor the environment variables to avoid duplication
  DATABASE_URI: "mariadb+pymysql://bunkerweb:REPLACEME_MYSQL@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:REPLACEME_TAG
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # For QUIC / HTTP3 support
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24" # Make sure to set the correct IP range so the scheduler can send the configuration to the instance
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:REPLACEME_TAG
    environment:
      <<: *ui-env
      BUNKERWEB_INSTANCES: "bunkerweb" # Make sure to set the correct instance name
      SERVER_NAME: "REPLACEME_DOMAIN"
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24" # We mirror the API_WHITELIST_IP from the bunkerweb service
      DNS_RESOLVERS: "127.0.0.1" # Use local DNS server
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      # Compression settings - Maximum performance
      USE_GZIP: "yes"
      GZIP_COMP_LEVEL: "9" # Maximum compression (1-9)
      GZIP_MIN_LENGTH: "1000"
      USE_BROTLI: "yes"
      BROTLI_COMP_LEVEL: "11" # Maximum compression (0-11)
      BROTLI_MIN_LENGTH: "1000"
      # Let's Encrypt configuration (will be enabled if DNS resolves correctly)
      AUTO_LETS_ENCRYPT: "REPLACEME_AUTO_LETS_ENCRYPT"
      EMAIL_LETS_ENCRYPT: "REPLACEME_EMAIL_LETS_ENCRYPT"
      LETS_ENCRYPT_CHALLENGE: "http"
      USE_LETS_ENCRYPT_STAGING: "no"
      # Web UI configuration (replace REPLACEME_DOMAIN with your actual domain)
      REPLACEME_DOMAIN_USE_TEMPLATE: "ui"
      REPLACEME_DOMAIN_USE_REVERSE_PROXY: "yes"
      REPLACEME_DOMAIN_REVERSE_PROXY_URL: "/REPLACEME_UI_PATH" # Custom path for UI access
      REPLACEME_DOMAIN_REVERSE_PROXY_HOST: "http://bw-ui:7000" # The web UI container is listening on the 7000 port by default
    volumes:
      - /data/BunkerWeb/storage:/data # This is used to persist the cache and other data like the backups
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:REPLACEME_TAG
    environment:
      <<: *ui-env
      # Automated admin credentials
      OVERRIDE_ADMIN_CREDS: "yes"
      ADMIN_USERNAME: "REPLACEME_ADMIN_USER"
      ADMIN_PASSWORD: "REPLACEME_ADMIN_PASS"
      FLASK_SECRET: "REPLACEME_FLASK"
      TOTP_SECRETS: "REPLACEME_DEFAULT"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "REPLACEME_MYSQL"
    volumes:
      - /data/BunkerWeb/database:/var/lib/mysql
    networks:
      - bw-db

# volumes: # Using host directories instead of named volumes

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db