# Author: Michal Koeckeis-Fresel
# License: MIT
# Sample application template for BunkerWeb
# Save this as /data/BunkerWeb/apps/sample-app.yml

services:
  # Example 1: Simple web application
  webapp:
    image: nginxdemos/nginx-hello
    networks:
      - bw-services
    labels:
      - "bunkerweb.SERVER_NAME=app.yourdomain.com"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://webapp:8080"
      - "bunkerweb.AUTO_LETS_ENCRYPT=yes"

  # Example 2: API with enhanced security
  api:
    image: your-api-image
    networks:
      - bw-services
    labels:
      - "bunkerweb.SERVER_NAME=api.yourdomain.com"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://api:3000"
      - "bunkerweb.AUTO_LETS_ENCRYPT=yes"
      - "bunkerweb.USE_MODSECURITY=yes"
      - "bunkerweb.USE_ANTIBOT=captcha"
      - "bunkerweb.USE_LIMIT_REQ=yes"
      - "bunkerweb.LIMIT_REQ_RATE=10r/s"

  # Example 3: WordPress with specific protections
  wordpress:
    image: wordpress:latest
    networks:
      - bw-services
    labels:
      - "bunkerweb.SERVER_NAME=blog.yourdomain.com"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://wordpress:80"
      - "bunkerweb.AUTO_LETS_ENCRYPT=yes"
      - "bunkerweb.USE_MODSECURITY=yes"
      - "bunkerweb.USE_ANTIBOT=javascript"
      - "bunkerweb.DENY_EVIL_USER_AGENT=yes"
      - "bunkerweb.USE_LIMIT_REQ=yes"

networks:
  bw-services:
    external: true
    name: bw-services