# BunkerWeb Autoconf Docker Compose Template (RELEASE CHANNEL SUPPORT)
#
# Copyright (c) 2025 Michal Koeckeis-Fresel
# 
# This software is dual-licensed under your choice of:
# - MIT License (see LICENSE-MIT)
# - GNU Affero General Public License v3.0 (see LICENSE-AGPL)
# 
# SPDX-License-Identifier: MIT OR AGPL-3.0-or-later

x-ui-env: &ui-env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:REPLACEME_MYSQL@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:REPLACEME_TAG
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:REPLACEME_TAG
    environment:
      <<: *ui-env
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: ""
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      DNS_RESOLVERS: "REPLACEME_DNS_RESOLVERS"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      HTTP3: "yes"
      HTTP3_ALT_SVC_PORT: "443"
      USE_GZIP: "yes"
      GZIP_COMP_LEVEL: "9"
      GZIP_MIN_LENGTH: "1000"
      USE_BROTLI: "yes"
      BROTLI_COMP_LEVEL: "11"
      BROTLI_MIN_LENGTH: "1000"
      USE_MODSECURITY_GLOBAL_CRS: "yes"
      SSL_PROTOCOLS: "TLSv1.2 TLSv1.3"
      #SSL_CIPHERS_CUSTOM: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305"
      # Blacklist Configuration
      USE_BLACKLIST: "yes"
      BLACKLIST_IP: ""
      BLACKLIST_RDNS: ".shodan.io .censys.io"
      BLACKLIST_RDNS_GLOBAL: "yes"
      BLACKLIST_ASN: ""
      BLACKLIST_USER_AGENT: ""
      BLACKLIST_URI: ""
      BLACKLIST_COUNTRY: ""
      BLACKLIST_IGNORE_IP: ""
      BLACKLIST_IGNORE_RDNS: ""
      BLACKLIST_IGNORE_ASN: ""
      BLACKLIST_IGNORE_USER_AGENT: ""
      BLACKLIST_IGNORE_URI: ""
      BLACKLIST_IP_URLS: "https://www.dan.me.uk/torlist/?exit https://iplists.firehol.org/files/firehol_level3.netset"
      BLACKLIST_RDNS_URLS: ""
      BLACKLIST_ASN_URLS: ""
      BLACKLIST_USER_AGENT_URLS: "https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-user-agents.list"
      BLACKLIST_URI_URLS: ""
      BLACKLIST_IGNORE_IP_URLS: ""
      BLACKLIST_IGNORE_RDNS_URLS: ""
      BLACKLIST_IGNORE_ASN_URLS: ""
      BLACKLIST_IGNORE_USER_AGENT_URLS: ""
      BLACKLIST_IGNORE_URI_URLS: ""
      # Allowlist Configuration
      USE_ALLOWLIST: "yes"
      ALLOWLIST_IP: ""
      ALLOWLIST_COUNTRY: ""
      ALLOWLIST_RDNS: ""
      ALLOWLIST_MODE: "block"
      ALLOWLIST_STATUS_CODE: "403"
      # Greylist Configuration
      USE_GREYLIST: "yes"
      GREYLIST_IP: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      GREYLIST_RDNS: ""
      # DNSBL Configuration
      USE_DNSBL: "yes"
      DNSBL_LIST: "bl.blocklist.de zen.spamhaus.org"
      AUTO_LETS_ENCRYPT: "REPLACEME_AUTO_LETS_ENCRYPT"
      EMAIL_LETS_ENCRYPT: "REPLACEME_EMAIL_LETS_ENCRYPT"
      LETS_ENCRYPT_CHALLENGE: "http"
      USE_LETS_ENCRYPT_STAGING: "yes"
      LETS_ENCRYPT_PROFILE: "shortlived"
      LETS_ENCRYPT_MAX_RETRIES: "0"
      REPLACEME_DOMAIN_USE_TEMPLATE: "ui"
      REPLACEME_DOMAIN_USE_REVERSE_PROXY: "yes"
      REPLACEME_DOMAIN_REVERSE_PROXY_URL: "/REPLACEME_UI_PATH"
      REPLACEME_DOMAIN_REVERSE_PROXY_HOST: "http://bw-ui:7000"
      # Demo site configuration (will be processed based on DEMOSITE setting)
      REPLACEME_DOMAIN_demo_USE_REVERSE_PROXY: "yes"
      REPLACEME_DOMAIN_demo_REVERSE_PROXY_URL: "/demo"
      REPLACEME_DOMAIN_demo_REVERSE_PROXY_HOST: "http://demo-app:80"
    volumes:
      - /data/BunkerWeb/storage:/data
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-db

  bw-autoconf:
    image: bunkerity/bunkerweb-autoconf:REPLACEME_TAG
    depends_on:
      - bw-docker
      - bw-scheduler
    environment:
      <<: *ui-env
      DOCKER_HOST: "tcp://bw-docker:2375"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-docker
      - bw-db

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    restart: "unless-stopped"
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:REPLACEME_TAG
    environment:
      <<: *ui-env
      # OVERRIDE_ADMIN_CREDS: "no"
      ADMIN_USERNAME: "REPLACEME_ADMIN_USERNAME"  
      ADMIN_PASSWORD: "REPLACEME_ADMIN_PASSWORD"
      FLASK_SECRET: "REPLACEME_FLASK_SECRET"
      TOTP_SECRETS: "REPLACEME_DEFAULT"
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "REPLACEME_MYSQL"
    volumes:
      - /data/BunkerWeb/database:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

  # Demo application (conditional - controlled by DEMOSITE configuration)
  demo-app:
    image: nginxdemos/nginx-hello
    container_name: demo-app
    restart: "unless-stopped"
    networks:
      - bw-services

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
  bw-db:
    name: bw-db