# BunkerWeb Autoconf Docker Compose Template (FIXED)

x-ui-env: &ui-env
  # We anchor the environment variables to avoid duplication
  DATABASE_URI: "mariadb+pymysql://bunkerweb:REPLACEME_MYSQL@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.1
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # For QUIC / HTTP3 support
    labels:
      - "bunkerweb.INSTANCE=yes" # We set the instance label to allow the autoconf to detect the instance
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24" # Will be automatically expanded by script
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.1
    environment:
      <<: *ui-env
      BUNKERWEB_INSTANCES: "bunkerweb" # Make sure to set the correct instance name
      SERVER_NAME: ""
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24" # Will be automatically expanded by script
      DNS_RESOLVERS: "127.0.0.11" # Use local DNS server
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      # Compression settings - Maximum performance
      USE_GZIP: "yes"
      GZIP_COMP_LEVEL: "9" # Maximum compression (1-9)
      GZIP_MIN_LENGTH: "1000"
      USE_BROTLI: "yes"
      BROTLI_COMP_LEVEL: "11" # Maximum compression (0-11)
      BROTLI_MIN_LENGTH: "1000"
      # Let's Encrypt configuration (will be enabled if DNS resolves correctly)
      AUTO_LETS_ENCRYPT: "REPLACEME_AUTO_LETS_ENCRYPT"
      EMAIL_LETS_ENCRYPT: "REPLACEME_EMAIL_LETS_ENCRYPT"
      LETS_ENCRYPT_CHALLENGE: "http"
      USE_LETS_ENCRYPT_STAGING: "yes"
      # Web UI configuration - FIXED: Will be replaced by script with actual domain and path
      REPLACEME_DOMAIN_USE_TEMPLATE: "ui"
      REPLACEME_DOMAIN_USE_REVERSE_PROXY: "yes"
      REPLACEME_DOMAIN_REVERSE_PROXY_URL: "REPLACEME_UI_PATH"
      REPLACEME_DOMAIN_REVERSE_PROXY_HOST: "http://bw-ui:7000"
    volumes:
      - /data/BunkerWeb/storage:/data # This is used to persist the cache and other data like the backups
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-db

  bw-autoconf:
    image: bunkerity/bunkerweb-autoconf:1.6.1
    depends_on:
      - bw-docker
      - bw-scheduler
    environment:
      <<: *ui-env
      DOCKER_HOST: "tcp://bw-docker:2375"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-docker
      - bw-db

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    restart: "unless-stopped"
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.1
    # Labels will be automatically added by script with proper domain and random UI path
    environment:
      <<: *ui-env
      # FIXED: Properly structured admin credentials (will be handled by script)
      # Optional: Automated admin credentials (uncomment to skip setup wizard)
      # OVERRIDE_ADMIN_CREDS: "no"
      ADMIN_USERNAME: "REPLACEME_ADMIN_USERNAME"  
      ADMIN_PASSWORD: "REPLACEME_ADMIN_PASSWORD"
      FLASK_SECRET: "REPLACEME_FLASK_SECRET"
      TOTP_SECRETS: "REPLACEME_DEFAULT"
    restart: "unless-stopped"
    depends_on:
      - bw-db
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "REPLACEME_MYSQL"
    volumes:
      - /data/BunkerWeb/database:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
  bw-db:
    name: bw-db