# BunkerWeb UI-Integrated Docker Compose Template (RELEASE CHANNEL SUPPORT)
#
# Copyright (c) 2025 Michal Koeckeis-Fresel
# 
# This software is dual-licensed under your choice of:
# - MIT License (see LICENSE-MIT)
# - GNU Affero General Public License v3.0 (see LICENSE-AGPL)
# 
# SPDX-License-Identifier: MIT OR AGPL-3.0-or-later

x-ui-env: &ui-env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:REPLACEME_MYSQL@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:REPLACEME_TAG
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:REPLACEME_TAG
    environment:
      <<: *ui-env
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "REPLACEME_DOMAIN"
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      DNS_RESOLVERS: "127.0.0.1"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      GZIP_COMP_LEVEL: "9"
      GZIP_MIN_LENGTH: "1000"
      USE_BROTLI: "yes"
      BROTLI_COMP_LEVEL: "11"
      BROTLI_MIN_LENGTH: "1000"
      AUTO_LETS_ENCRYPT: "REPLACEME_AUTO_LETS_ENCRYPT"
      EMAIL_LETS_ENCRYPT: "REPLACEME_EMAIL_LETS_ENCRYPT"
      LETS_ENCRYPT_CHALLENGE: "http"
      USE_LETS_ENCRYPT_STAGING: "no"
      REPLACEME_DOMAIN_USE_TEMPLATE: "ui"
      REPLACEME_DOMAIN_USE_REVERSE_PROXY: "yes"
      REPLACEME_DOMAIN_REVERSE_PROXY_URL: "/REPLACEME_UI_PATH"
      REPLACEME_DOMAIN_REVERSE_PROXY_HOST: "http://bw-ui:7000"
    volumes:
      - /data/BunkerWeb/storage:/data
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:REPLACEME_TAG
    environment:
      <<: *ui-env
      OVERRIDE_ADMIN_CREDS: "yes"
      ADMIN_USERNAME: "REPLACEME_ADMIN_USER"
      ADMIN_PASSWORD: "REPLACEME_ADMIN_PASS"
      FLASK_SECRET: "REPLACEME_FLASK"
      TOTP_SECRETS: "REPLACEME_DEFAULT"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "REPLACEME_MYSQL"
    volumes:
      - /data/BunkerWeb/database:/var/lib/mysql
    networks:
      - bw-db

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db