# BunkerWeb Autoconf Docker Compose Template with Redis, Let's Encrypt Support and Release Channel Support

x-ui-env: &bw-ui-env
  # We anchor the environment variables to avoid duplication
  AUTOCONF_MODE: "yes"
  DATABASE_URI: "mariadb+pymysql://bunkerweb:REPLACEME_MYSQL@bw-db:3306/db"

x-redis-env: &redis-env
  # Redis configuration for cluster mode
  USE_REDIS: "yes"
  REDIS_HOST: "bw-redis"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_SSL: "no"
  REDIS_SSL_VERIFY: "no"
  REDIS_TIMEOUT: "1000"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: "REPLACEME_REDIS_PASSWORD"
  REDIS_KEEPALIVE_IDLE: "30000"
  REDIS_KEEPALIVE_POOL: "10"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:REPLACEME_TAG
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # For QUIC / HTTP3 support
    labels:
      - "bunkerweb.INSTANCE=yes" # We set the instance label to allow the autoconf to detect the instance
    environment:
      <<: *redis-env
      AUTOCONF_MODE: "yes"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      # Syslog Configuration
      USE_SYSLOG: "yes"
      SYSLOG_HOST: "bw-syslog"
      SYSLOG_PORT: "5514"
      SYSLOG_FACILITY: "local0"
    restart: "unless-stopped"
    depends_on:
      - bw-redis
      - bw-db
      - bw-syslog
    networks:
      - bw-universe
      - bw-services
      - bw-redis

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:REPLACEME_TAG
    environment:
      <<: [*bw-ui-env, *redis-env]
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "REPLACEME_DOMAIN"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      MULTISITE: "yes"
      UI_HOST: "http://bw-ui:7000" # Change it if needed
      # Let's Encrypt Configuration
      AUTO_LETS_ENCRYPT: "REPLACEME_AUTO_LETS_ENCRYPT"
      EMAIL_LETS_ENCRYPT: "REPLACEME_EMAIL_LETS_ENCRYPT"
      LETS_ENCRYPT_CHALLENGE: "http"
      USE_LETS_ENCRYPT_STAGING: "yes"
      # DNS Resolvers for domain validation
      DNS_RESOLVERS: "1.1.1.1 8.8.8.8"
      # Additional SSL/TLS settings
      USE_HTTPS: "yes"
      HTTPS_PROTOCOLS: "TLSv1.2 TLSv1.3"
      HTTP2: "yes"
      # Syslog Configuration
      USE_SYSLOG: "yes"
      SYSLOG_HOST: "bw-syslog"
      SYSLOG_PORT: "5514"
      SYSLOG_FACILITY: "local0"
    volumes:
      - /data/BunkerWeb/storage:/data # This is used to persist the cache and other data like the backups
    restart: "unless-stopped"
    depends_on:
      - bw-redis
      - bw-db
      - bw-syslog
    networks:
      - bw-universe
      - bw-db
      - bw-redis

  bw-autoconf:
    image: bunkerity/bunkerweb-autoconf:REPLACEME_TAG
    depends_on:
      - bw-docker
      - bw-scheduler
      - bw-syslog
    environment:
      <<: [*bw-ui-env, *redis-env]
      DOCKER_HOST: "tcp://bw-docker:2375"
      # Syslog Configuration
      USE_SYSLOG: "yes"
      SYSLOG_HOST: "bw-syslog"
      SYSLOG_PORT: "5514"
      SYSLOG_FACILITY: "local0"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-docker
      - bw-db
      - bw-redis

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:REPLACEME_TAG
    environment:
      <<: [*bw-ui-env, *redis-env]
      # Optional: Automated admin credentials (uncomment to skip setup wizard)
      # OVERRIDE_ADMIN_CREDS: "yes"
      # ADMIN_USERNAME: "admin"
      # ADMIN_PASSWORD: "REPLACEME_ADMIN"
      # FLASK_SECRET: "REPLACEME_FLASK"
      TOTP_SECRETS: "REPLACEME_DEFAULT"
      # Syslog Configuration
      USE_SYSLOG: "yes"
      SYSLOG_HOST: "bw-syslog"
      SYSLOG_PORT: "5514"
      SYSLOG_FACILITY: "local0"
    restart: "unless-stopped"
    depends_on:
      - bw-redis
      - bw-db
      - bw-syslog
    networks:
      - bw-universe
      - bw-db
      - bw-redis

  bw-redis:
    image: redis:7-alpine
    command: >
      redis-server
      --requirepass "REPLACEME_REDIS_PASSWORD"
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1 300 10 60 10000
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --tcp-keepalive 300
      --timeout 300
    volumes:
      - /data/BunkerWeb/redis:/data
    restart: unless-stopped
    networks:
      - bw-redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "REPLACEME_MYSQL"
    volumes:
      - /data/BunkerWeb/database:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

  bw-syslog:
    image: lscr.io/linuxserver/syslog-ng:latest
    environment:
      - PUID=101
      - PGID=101
      - TZ=Etc/UTC
    ports:
      - "514:5514/udp"
      - "601:6601/tcp"
      - "6514:6514/tcp"
    volumes:
      - /data/BunkerWeb/logs:/var/log
      - /data/BunkerWeb/syslog-config:/config
    restart: unless-stopped
    networks:
      - bw-universe
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
  bw-db:
    name: bw-db
  bw-redis:
    name: bw-redis